# Generated by Django 3.0.3 on 2020-06-28 11:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200624_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='内容'),
        ),
    ]
