# Generated by Django 3.0.3 on 2020-06-28 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('goods', '0004_auto_20200628_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsimage',
            name='goods',
        ),
        migrations.AddField(
            model_name='goodsimage',
            name='content_type',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='goodsimage',
            name='object_id',
            field=models.PositiveIntegerField(default=14),
            preserve_default=False,
        ),
    ]
