# Generated by Django 3.0.3 on 2020-06-28 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('goods', '0005_auto_20200628_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimage',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='类型'),
        ),
    ]
