# Generated by Django 3.0.3 on 2020-04-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_staff',
            field=models.IntegerField(default=0, verbose_name='是否为员工'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_superuser',
            field=models.IntegerField(default=0, verbose_name='是否为超管'),
        ),
    ]
